package model;

import java.security.SecureRandom;

/**
 * Die Klasse IvGenerator, zum generieren von IVs.
 * @author Stefan Böhling
 */
public class IvGenerator {
	
	/**
	 * Instantiates a new iv generator.
	 */
	public IvGenerator() {

	}
	
	/**
	 * Generate iv bytes with the specified size.
	 *
	 * @param blockSize the block size
	 * @return the generated byte[]
	 */
	public byte[] generateIvBytes(int blockSize){
		SecureRandom random = new SecureRandom();
		byte[] iv = new byte[blockSize];
		random.nextBytes(iv);
		return iv;
	}
}
